USE [master]
GO

/****** Object:  Database [EngDb-XS]    Script Date: 8/27/2019 9:45:21 AM ******/
CREATE DATABASE [EngDb-XS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EngDb-XS', FILENAME = N'D:\DBDATA\EngDb-XS.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EngDb-XS_log', FILENAME = N'D:\DBDATA\LOGS\EngDb-XS_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EngDb-XS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EngDb-XS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EngDb-XS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EngDb-XS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EngDb-XS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EngDb-XS] SET ARITHABORT OFF 
GO

ALTER DATABASE [EngDb-XS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EngDb-XS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EngDb-XS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EngDb-XS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EngDb-XS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EngDb-XS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EngDb-XS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EngDb-XS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EngDb-XS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EngDb-XS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EngDb-XS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EngDb-XS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EngDb-XS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EngDb-XS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EngDb-XS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EngDb-XS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EngDb-XS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EngDb-XS] SET RECOVERY FULL 
GO

ALTER DATABASE [EngDb-XS] SET  MULTI_USER 
GO

ALTER DATABASE [EngDb-XS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EngDb-XS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EngDb-XS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EngDb-XS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EngDb-XS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EngDb-XS] SET QUERY_STORE = OFF
GO

USE [EngDb-XS]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [EngDb-XS] SET  READ_WRITE 
GO

