USE [master]
GO

/****** Object:  Database [NewLine ]    Script Date: 7/25/2019 10:11:43 AM ******/
CREATE DATABASE [NewLine ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NewLine', FILENAME = N'D:\DBDATA\NewLine .mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NewLine _log', FILENAME = N'D:\DBDATA\LOGS\NewLine _log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewLine ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NewLine ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NewLine ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NewLine ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NewLine ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NewLine ] SET ARITHABORT OFF 
GO

ALTER DATABASE [NewLine ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NewLine ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NewLine ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NewLine ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NewLine ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NewLine ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NewLine ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NewLine ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NewLine ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NewLine ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NewLine ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NewLine ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NewLine ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NewLine ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NewLine ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NewLine ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NewLine ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NewLine ] SET RECOVERY FULL 
GO

ALTER DATABASE [NewLine ] SET  MULTI_USER 
GO

ALTER DATABASE [NewLine ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NewLine ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NewLine ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NewLine ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NewLine ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NewLine ] SET QUERY_STORE = OFF
GO

USE [NewLine ]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [NewLine ] SET  READ_WRITE 
GO

