USE [master]
GO

/****** Object:  Database [Pac-LiteDb ]    Script Date: 7/25/2019 10:11:33 AM ******/
CREATE DATABASE [Pac-LiteDb ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pac-LiteDb', FILENAME = N'D:\DBDATA\Pac-LiteDb .mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pac-LiteDb _log', FILENAME = N'D:\DBDATA\LOGS\Pac-LiteDb _log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pac-LiteDb ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pac-LiteDb ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pac-LiteDb ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pac-LiteDb ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Pac-LiteDb ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pac-LiteDb ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET RECOVERY FULL 
GO

ALTER DATABASE [Pac-LiteDb ] SET  MULTI_USER 
GO

ALTER DATABASE [Pac-LiteDb ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pac-LiteDb ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pac-LiteDb ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pac-LiteDb ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Pac-LiteDb ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pac-LiteDb ] SET QUERY_STORE = OFF
GO

USE [Pac-LiteDb ]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Pac-LiteDb ] SET  READ_WRITE 
GO

